[package]
name = "VkWizard"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ash = { version = "0.38.0", features = ["linked"] }
sdl2 = "0.38.0"
smallvec = "1.15.1"
thiserror = "2.0.17"
vulkano = "0.35.2"
